### ISSUE TITLE
Detection sur image fixe

### ISSUE THREAD

**Issue by guenneguezt** [mika-nt28/Jeedom-OpenALPR#14]
Bonjour,

En fait le plugin étant fortement consommateur, j'ai développé le plugin ftpd.
Serait-il envisageable de configurer une détection sur image fixe dont le nom viendrait d'une commande Jeedom ?

A+
Thomas

**Comment by mika-nt28** [comment]
Il est envisageable effectivement de faire une detection sur image fixe.
OpenAlpr le fait tres bien avec simplement une requet du type #alpr ./samplecar.png
Il faut que je réfléchisse a comment je peux intégrer ça dans le plugin

**Comment by mika-nt28** [comment]
Ajouté sue la prochaine release
