### ISSUE TITLE
Patterne d'identification de plaque

### ISSUE THREAD

**Issue by guenneguezt** [mika-nt28/Jeedom-OpenALPR#3]
Ajouter une paterne de plaque d'imatriculation pour éviter de créer des plaques à tout va dans le groupe "Plaques détectées inconnu".

**Comment by mika-nt28** [comment]
Je pense que cela existe deja https://jeedom.github.io/documentation/third_plugin/openalpr/fr_FR/index.html#_plaques_d_imatriculation

**Comment by guenneguezt** [comment]
Bonjour,
Non pas dans ce sens, mais dans le sens, éviter qu'il ne crée dans le groupe plaque inconnue plein de plaque qui ne sont pas logique.
A+
Thomas

**Comment by mika-nt28** [comment]
Par ce qu'il te retourne des plaques illogique?
C'est vrai que j'ai desactivé chez moi cette possibilité car elle créait trop de commande.

**Comment by guenneguezt** [comment]
Oui plein ...
A un tel point que je ne peux plus consulter à distance le groupe ;-)

**Comment by mika-nt28** [comment]
J'ai poussé cette mise a jours avec l'ajout d'un controle de validité de plaque
