### ISSUE TITLE
"500 : Internal Server Error"  sur groupe "Plaques détectées"

### ISSUE THREAD

**Issue by lcoulon** [mika-nt28/Jeedom-openalpr#72]
Bonjour

Lorsque je vais sur le groupe 'Plaques détectées' j'ai l'erreur "500 : Internal Server Error"

Que faire svp ?

De plus, dans les snapshot, j'ai parfois des images floues, souvent que le haut ou le bas de l'image est nette mais le reste est flouté, sauriez vous me dire pourquoi ?

Merci a vous

**Comment by mika-nt28** [comment]
Desolé je n'ai pas recue de notification sur cette issue.
Est ce que le defaut est toujours présent?
Dans le log http.error il doit y avoir plus d'info sur cette erreur 500.

Les images floues ou avec des pixel bisard c'est souvant un flux trop rapide ou un surcharge CPU

**Comment by mika-nt28** [comment]
Est ce que cette erreur est toujours présente?
